spring:
  devtools:
    restart:
      enabled: true
  resources:
    chain:
      cache: false
  freemarker:
    cache: false
    charset: UTF-8
    content-type: text/html
    request-context-attribute: req
    expose-request-attributes: false
    expose-session-attributes: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/member-manage?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Awm96lgq
    hikari:
      allow-pool-suspension: true
      auto-commit: false
      maximum-pool-size: 5
      minimum-idle: 2
      connection-test-query: select 1
  mvc:
    favicon:
      enabled: false
  application:
    name: member-manage
  output:
    ansi:
      enabled: DETECT
  jmx:
    enabled: false

server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  display-name: member-manage
  ssl:
    enabled: false
  port: 80

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    default-executor-type: simple
    lazy-loading-enabled: false
  type-aliases-package: cn.lgq.mm.model
  mapper-locations: classpath:mapper/*.xml

mapper:
  identity: mysql
  not-empty: false
#  mappers: cn.lgq.mm.dao.TodoDao

#system custom properties
system:
  regulation:
    storePresentRule:
      100: 200
      200: 500
      500: 1000
    consumeReturnRatio: 1
  tasks:
    integralPresentTaskCron: 15 15 0 1 * *